//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo1.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class acarsEntities : DbContext
    {
        public acarsEntities()
            : base("name=acarsEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<nacarsdata01> nacarsdata01 { get; set; }
        public virtual DbSet<nacarsdata02> nacarsdata02 { get; set; }
        public virtual DbSet<nacarsdata03> nacarsdata03 { get; set; }
        public virtual DbSet<nacarsdata04> nacarsdata04 { get; set; }
        public virtual DbSet<nacarsdata05> nacarsdata05 { get; set; }
        public virtual DbSet<nacarsdata06> nacarsdata06 { get; set; }
        public virtual DbSet<nacarsdata07> nacarsdata07 { get; set; }
        public virtual DbSet<nacarsdata08> nacarsdata08 { get; set; }
        public virtual DbSet<nacarsdata09> nacarsdata09 { get; set; }
        public virtual DbSet<nacarsdata10> nacarsdata10 { get; set; }
        public virtual DbSet<nacarsdata11> nacarsdata11 { get; set; }
        public virtual DbSet<nacarsdata12> nacarsdata12 { get; set; }
        public virtual DbSet<nacarsdata13> nacarsdata13 { get; set; }
        public virtual DbSet<nacarsdata14> nacarsdata14 { get; set; }
        public virtual DbSet<nacarsdata15> nacarsdata15 { get; set; }
        public virtual DbSet<nacarsdata16> nacarsdata16 { get; set; }
        public virtual DbSet<nacarsdata17> nacarsdata17 { get; set; }
        public virtual DbSet<nacarsdata18> nacarsdata18 { get; set; }
        public virtual DbSet<nacarsdata19> nacarsdata19 { get; set; }
        public virtual DbSet<nacarsdata20> nacarsdata20 { get; set; }
        public virtual DbSet<nacarsdata21> nacarsdata21 { get; set; }
        public virtual DbSet<nacarsdata22> nacarsdata22 { get; set; }
        public virtual DbSet<nacarsdata23> nacarsdata23 { get; set; }
        public virtual DbSet<nacarsdata24> nacarsdata24 { get; set; }
        public virtual DbSet<nacarsdata25> nacarsdata25 { get; set; }
        public virtual DbSet<nacarsdata26> nacarsdata26 { get; set; }
        public virtual DbSet<nacarsdata27> nacarsdata27 { get; set; }
        public virtual DbSet<nacarsdata28> nacarsdata28 { get; set; }
        public virtual DbSet<nacarsdata29> nacarsdata29 { get; set; }
        public virtual DbSet<nacarsdata30> nacarsdata30 { get; set; }
        public virtual DbSet<nacarsdata31> nacarsdata31 { get; set; }
        public int nlong { get; set; }
        public int nlat { get; set; }
        public int nwinddirection { get; set; }
        public int nwindspeed { get; set; }
        public int? ntemperature { get; set; }
    }
}
