//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo1.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class nacarsdata15 : acarsEntities
    {
        public int nindex { get; set; }
        public string nregister { get; set; }
        public string nflightnum { get; set; }
        public Nullable<double> nlat { get; set; }
        public Nullable<double> nlong { get; set; }
        public Nullable<int> naltitude { get; set; }
        public Nullable<double> ntemperature { get; set; }
        public Nullable<int> nwinddirection { get; set; }
        public Nullable<double> nwindspeed { get; set; }
        public Nullable<System.DateTime> ndatetime { get; set; }
        public string nsrcreport { get; set; }
    }
}
